name: Build Site

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.9
        cache: 'pip'
              
    - name: Install Requirements
      run: python3 -m pip install --upgrade pip && pip3 install -r requirements.txt

    - name: Build Artifact
      run: ./scripts/build.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pros-docs
        path: ./build